CREATE TABLE IF NOT EXISTS playtime.total_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collector_id text NOT NULL REFERENCES playtime.collectors(collector_id) ON DELETE CASCADE,
  source text NOT NULL CHECK (source IN ('steam', 'modrinth')),
  game_id text NOT NULL,
  minutes bigint NOT NULL CHECK (minutes BETWEEN 0 AND 100000000),
  recorded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS total_history_lookup_idx
  ON playtime.total_history (collector_id, source, game_id, recorded_at DESC, history_id DESC);

INSERT INTO playtime.total_history (collector_id, source, game_id, minutes, recorded_at)
SELECT collector_id, source, game_id, minutes, now()
FROM playtime.totals;
